#! /usr/bin/bash -i

# setup dotfile management using stow
echo -e "${YELLOW}Setting up dotfiles with stow...${NC}"
DOTFILES_DIR="$HOME/dotfiles"

# List of dotfiles to stow
git clone $REPO $DOTFILES_DIR || true
stow .
echo -e "${GREEN}Dotfiles setup completed!${NC}"